[package]
name = "muso"
version = "1.4.0"
authors = [ "Kevin <quebin31@gmail.com>" ]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ansi_term = "0.12.1"
anyhow = "1"
cfg-if = "0.1"
clap = "2"
common_macros = "0.1"
dirs = "2"
human-panic = "1"
id3 = "0.5.0"
infer = "0.1"
lazy_static = "1"
log = "0.4.8"
metaflac = "0.2"
nom = "5"
notify = "4"
shellexpand = "2"
thiserror = "1"
toml = "0.5"

[dependencies.serde]
version = "1"
features = [ "derive" ]

[features]
default = [ ]
standalone = [ ]
