[package]
name = "muso"
version = "1.2.0"
authors = ["Kevin <quebin31@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
infer = "0.1.4"
id3 = "0.5.0"
metaflac = "0.2.1"
rayon = "1"
clap = "2"
dirs = "2"
shellexpand = "1"
notify = "4"
log = "0.4.8"
ansi_term = "0.12.1"
human-panic = "1"

[dependencies.config]
version = "0.10.1"
default-features = false 
features = [ "toml" ]

[features]
default = []
standalone = []
