[config]
watch = [ 'default','test' ]

[libraries.default]
format = '{artist}/{album}/{track} - {title}.{ext}'
folders = ['$HOME/Music']

[libraries.test]
format = '{artist}/{album}/{track} - {title}.{ext}'
folders = [ '$HOME/Projects/Rust/muso/music' ]


