name: Build (and publish)

on:
  push:
    branches:
      - master
    tags:
      - "*"

env:
  GIT_SSH_COMMAND: ssh -i $HOME/.ssh/aur -o UserKnownHostsFile=$HOME/.ssh/known_hosts

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/heads/')
    container:
      image: rust:latest

    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: cargo build
      - name: Run tests
        run: cargo test

  build_and_publish:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    container:
      image: rust:latest

    steps:
      - uses: actions/checkout@v2
      - name: Init SSH key and hosts
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_AUR_KEY }}
          name: aur
          known_hosts: ${{ secrets.KNOWN_HOSTS_AUR }}
      - name: Checkout pkgbuild submodule
        run: git submodule update --init --force --depth=1
      - name: Run tests
        run: cargo test
      - name: Build binary
        run: cargo build --release
      - name: Generate tarball
        run: tar czf release.tar.gz share target/release/muso
      - name: Update PKGBUILD
        run: |
          sha256sum=$(sha256sum release.tar.gz | cut -d ' ' -f1)
          version=$(echo $GITHUB_REF | cut -d '/' -f3)
          cd pkgbuild

          sed -i -E "s/(pkgver=).*/\1$version/" PKGBUILD
          sed -i -E "s/(pkgrel=).*/\11/" PKGBUILD
          sed -i -E "s/(sha256sums=).*/\1('$sha256sum')/" PKGBUILD
      - name: Generate .SRCINFO
        uses: ./.github/actions/generate_srcinfo
        with:
          target: pkgbuild
      - name: Publish to AUR
        run: |
          cd pkgbuild

          version=$(echo $GITHUB_REF | cut -d '/' -f3)
          git config --local user.email "quebin31@gmail.com"
          git config --local user.name "Kevin (CI/CD)"
          git commit -m "updver: $version" -a
          git push origin HEAD:refs/heads/master
      - name: Publish to GitHub
        uses: softprops/action-gh-release@v1
        with:
          files: release.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
