name: Build binary

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: rust:latest

    steps:
      - uses: actions/checkout@v2
      - name: Run tests
        run: cargo test
      - name: Build release
        run: cargo build --release
      - name: Generate tarball
        run: tar czf release.tar.gz share target/release/muso
      - name: Release tarball
        uses: Roang-zero1/github-upload-release-artifacts-action@master
        with:
          args: release.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
