name: Build binary

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: rust:latest

    steps:
      - uses: actions/checkout@v2
      - name: Build release
        run: cargo build --release
      - name: Run tests
        run: cargo test --verbose
