name: Build binary

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: rust:latest

    steps:
      - uses: actions/checkout@v2
      - name: Run tests
        run: cargo test
      - name: Build release
        run: cargo build --release
      - name: Generate tarball
        run: |
          tar czf release.tar.gz share __w/muso/muso
      - uses: actions/upload-artifact@v1
        with:
          name: release
          path: release.tar.gz
