name: Build binary

on:
  push:
    branches:
      - master
#  release:
#    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: rust:latest

    steps:
      - uses: actions/checkout@v2
      - name: Run tests
        run: cargo test
      - name: Build release
        run: cargo build --release
      - name: Generate tarball
        run: |
          ls -la
          tar czf release.tar.gz share
      - uses: actions/upload-artifact@v1
        with:
          name: release
          path: release.tar.gz
